### ISSUE TITLE
勘误：打印错误

### ISSUE THREAD

**Issue by ljk5403** [hust-feiyue/hust-feiyue.github.io#1]
在2019年飞跃手册的第13页，1.2.3 2)的第一点中，

>大体来说，准备PhD的难度……原因在于PhD需要耗时费力的**陶瓷**

此处**陶瓷**可是**套瓷**？

**Comment by XiongchaoChen** [comment]
回答楼上同学的问题：
套磁 = 套瓷 = 陶瓷
语言用法的不同，不必纠结

**Comment by ljk5403** [comment]
谢谢！
