### ISSUE TITLE
添加华中大电气飞跃手册友情链接

### ISSUE THREAD

**Issue by lgx98** [hust-feiyue/hust-feiyue.github.io#3]
华中大电气飞跃手册2020已经发布，链接如下：
https://github.com/LHYi/Feiyue_for_ECE
同为ECE，电气学院的申请经验对学弟学妹们而言也有借鉴意义。

**Comment by hust-feiyue** [comment]
感谢，我会和我们这边的小伙伴说的。

**Comment by hust-feiyue** [comment]
> 华中大电气飞跃手册2020已经发布，链接如下：
> https://github.com/LHYi/Feiyue_for_ECE
> 同为ECE，电气学院的申请经验对学弟学妹们而言也有借鉴意义。

您好，在@xyyuhans的帮助下已经更新页面，加上了电气的飞跃手册。以后可以直接合办，我看前面的基本知识部分是完全重叠的。
