### ISSUE TITLE
关于传播协议与侵权警告和手册格式的建议

### ISSUE THREAD

**Issue by xyyuhans** [hust-feiyue/hust-feiyue.github.io#4]
首先感谢一下参与飞跃手册编辑的每位人员，你们辛苦了。在这里提两个建议：
- 根据[传播协议与侵权警告](https://hust-feiyue.github.io/warning.html)
>本手册作为开源项目免费供给所有社会单位参考使用

可是飞跃手册很明显并没有开放源代码，只能内部人员编辑。解决方法有两种，一是公布源代码，二是将开源两个字去掉，换作其他许可证，比如“署名-非商业性使用-相同方式共享许可证”的[CC BY-SA-NC](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh-Hans)，也可以参考[华科电气飞跃手册的版权声明](https://github.com/LHYi/Feiyue_for_ECE)。
- 在申请总结与感想一块，读每个人的感想时，需要往前翻到案例库才能了解到申请人的背景，不方便，建议在感想那里附上每个人的背景

**Comment by hust-feiyue** [comment]
1、可以，你自己改就行，merge之前发我看一下
2、案例和总结感想不是一一对应的。
